// @generated by tools/gen-fixtures/gen_matrix.py — DO NOT EDIT BY HAND.
// Source of truth: pinned VeraCrypt checkout VeraCrypt_1.26.24 (tools/gen-fixtures/PIN).
// Rerun the generator after bumping the pin; review the diff like any code.
//
// Layer order in `layers` is innermost-first: "AES(Twofish)" means Twofish
// is applied to the plaintext first, then AES. Verify against fixtures
// before the first data-path test (vc-types/src/registry.rs note).

use super::{Cipher, EncryptionScheme, Prf};

pub static ENCRYPTION_SCHEMES: &[EncryptionScheme] = &[
    EncryptionScheme {
        name: "AES",
        layers: &[Cipher::Aes],
    },
    EncryptionScheme {
        name: "Serpent",
        layers: &[Cipher::Serpent],
    },
    EncryptionScheme {
        name: "Twofish",
        layers: &[Cipher::Twofish],
    },
    EncryptionScheme {
        name: "Camellia",
        layers: &[Cipher::Camellia],
    },
    EncryptionScheme {
        name: "Kuznyechik",
        layers: &[Cipher::Kuznyechik],
    },
    EncryptionScheme {
        name: "AES(Twofish)",
        layers: &[Cipher::Twofish, Cipher::Aes],
    },
    EncryptionScheme {
        name: "AES(Twofish(Serpent))",
        layers: &[Cipher::Serpent, Cipher::Twofish, Cipher::Aes],
    },
    EncryptionScheme {
        name: "Serpent(AES)",
        layers: &[Cipher::Aes, Cipher::Serpent],
    },
    EncryptionScheme {
        name: "Serpent(Twofish(AES))",
        layers: &[Cipher::Aes, Cipher::Twofish, Cipher::Serpent],
    },
    EncryptionScheme {
        name: "Twofish(Serpent)",
        layers: &[Cipher::Serpent, Cipher::Twofish],
    },
    EncryptionScheme {
        name: "Camellia(Kuznyechik)",
        layers: &[Cipher::Kuznyechik, Cipher::Camellia],
    },
    EncryptionScheme {
        name: "Kuznyechik(Twofish)",
        layers: &[Cipher::Twofish, Cipher::Kuznyechik],
    },
    EncryptionScheme {
        name: "Camellia(Serpent)",
        layers: &[Cipher::Serpent, Cipher::Camellia],
    },
    EncryptionScheme {
        name: "Kuznyechik(AES)",
        layers: &[Cipher::Aes, Cipher::Kuznyechik],
    },
    EncryptionScheme {
        name: "Kuznyechik(Serpent(Camellia))",
        layers: &[Cipher::Camellia, Cipher::Serpent, Cipher::Kuznyechik],
    },
];

pub static PRFS: &[Prf] = &[
    Prf {
        name: "SHA-512",
        default_iterations: 500_000,
        popularity_rank: 0,
    },
    Prf {
        name: "SHA-256",
        default_iterations: 500_000,
        popularity_rank: 1,
    },
    Prf {
        name: "BLAKE2s-256",
        default_iterations: 500_000,
        popularity_rank: 2,
    },
    Prf {
        name: "Whirlpool",
        default_iterations: 500_000,
        popularity_rank: 3,
    },
    Prf {
        name: "Streebog",
        default_iterations: 500_000,
        popularity_rank: 4,
    },
];
